import Head from "next/head";
import Image from "next/image";
import { useSelector } from "react-redux";
import HomeBanner from "../components/layouts/HomeBanner";
import ProductGrid from "../components/Products/ProductGrid";

export default function Home() {
  const profile = useSelector((state) => state.profile);
  const products = useSelector((state) => state.product.products);
  return (
    <div className="min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-7xl mx-auto px-2 py-10">
        {/* <HomeBanner /> */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 w-full gap-10 z-10">
          {products.map((product) => (
            <ProductGrid product={product} key={product.id} />
          ))}
        </div>
      </div>
    </div>
  );
}
