import Head from "next/head";
import Image from "next/image";
import { useSelector } from "react-redux";

export default function Home() {
  const profile = useSelector((state) => state.profile);

  console.log(profile);
  return (
    <div className="min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className="text-indigo-400">hello</p>
    </div>
  );
}
